spring:
 thymeleaf:
   cache: false
 security:
   oauth2:
     client:
       registration:
         okta:
           client-id: 0oaf9ftvj4JB9vPbD0h7
           client-secret: TxAcvn_IbfdkO_r-StyLS2ac0ABHaVjO6vndd6a0
       provider:
         okta:
           authorization-uri: https://dev-436030.oktapreview.com/oauth2/default/v1/authorize
           token-uri: https://dev-436030.oktapreview.com/oauth2/default/v1/token
           user-info-uri: https://dev-436030.oktapreview.com/oauth2/default/v1/userinfo
           jwk-set-uri: https://dev-436030.oktapreview.com/oauth2/default/v1/keys